require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShippingBoxesController do

  # This should return the minimal set of attributes required to create a valid
  # ShippingBox. As you add validations to ShippingBox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "height" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShippingBoxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shipping_boxes as @shipping_boxes" do
      shipping_box = ShippingBox.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shipping_boxes).should eq([shipping_box])
    end
  end

  describe "GET show" do
    it "assigns the requested shipping_box as @shipping_box" do
      shipping_box = ShippingBox.create! valid_attributes
      get :show, {:id => shipping_box.to_param}, valid_session
      assigns(:shipping_box).should eq(shipping_box)
    end
  end

  describe "GET new" do
    it "assigns a new shipping_box as @shipping_box" do
      get :new, {}, valid_session
      assigns(:shipping_box).should be_a_new(ShippingBox)
    end
  end

  describe "GET edit" do
    it "assigns the requested shipping_box as @shipping_box" do
      shipping_box = ShippingBox.create! valid_attributes
      get :edit, {:id => shipping_box.to_param}, valid_session
      assigns(:shipping_box).should eq(shipping_box)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShippingBox" do
        expect {
          post :create, {:shipping_box => valid_attributes}, valid_session
        }.to change(ShippingBox, :count).by(1)
      end

      it "assigns a newly created shipping_box as @shipping_box" do
        post :create, {:shipping_box => valid_attributes}, valid_session
        assigns(:shipping_box).should be_a(ShippingBox)
        assigns(:shipping_box).should be_persisted
      end

      it "redirects to the created shipping_box" do
        post :create, {:shipping_box => valid_attributes}, valid_session
        response.should redirect_to(ShippingBox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shipping_box as @shipping_box" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingBox.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_box => { "height" => "invalid value" }}, valid_session
        assigns(:shipping_box).should be_a_new(ShippingBox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingBox.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_box => { "height" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shipping_box" do
        shipping_box = ShippingBox.create! valid_attributes
        # Assuming there are no other shipping_boxes in the database, this
        # specifies that the ShippingBox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShippingBox.any_instance.should_receive(:update_attributes).with({ "height" => "" })
        put :update, {:id => shipping_box.to_param, :shipping_box => { "height" => "" }}, valid_session
      end

      it "assigns the requested shipping_box as @shipping_box" do
        shipping_box = ShippingBox.create! valid_attributes
        put :update, {:id => shipping_box.to_param, :shipping_box => valid_attributes}, valid_session
        assigns(:shipping_box).should eq(shipping_box)
      end

      it "redirects to the shipping_box" do
        shipping_box = ShippingBox.create! valid_attributes
        put :update, {:id => shipping_box.to_param, :shipping_box => valid_attributes}, valid_session
        response.should redirect_to(shipping_box)
      end
    end

    describe "with invalid params" do
      it "assigns the shipping_box as @shipping_box" do
        shipping_box = ShippingBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_box.to_param, :shipping_box => { "height" => "invalid value" }}, valid_session
        assigns(:shipping_box).should eq(shipping_box)
      end

      it "re-renders the 'edit' template" do
        shipping_box = ShippingBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_box.to_param, :shipping_box => { "height" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shipping_box" do
      shipping_box = ShippingBox.create! valid_attributes
      expect {
        delete :destroy, {:id => shipping_box.to_param}, valid_session
      }.to change(ShippingBox, :count).by(-1)
    end

    it "redirects to the shipping_boxes list" do
      shipping_box = ShippingBox.create! valid_attributes
      delete :destroy, {:id => shipping_box.to_param}, valid_session
      response.should redirect_to(shipping_boxes_url)
    end
  end

end
